name: lint, test and deploy
on: push
jobs:
  lint:
    runs-on: 
    steps:
      - name:
        run:
  test:
    runs-on: 
    steps:
      - name:
        run:
  deploy:
    runs-on: 
    steps:
      - name:
        run:
